<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="oculus_remnant">

	<xacro:include filename="$(find oculus_remnant)/urdf/asus_camera.urdf.xacro"/>

	<xacro:property name="base_length" value="0.17" />
	<xacro:property name="base_width" value="0.105" />
	<xacro:property name="base_height" value="0.043" />
	<xacro:property name="wheel_radius" value="0.0235" />
	<xacro:property name="wheel_width" value="0.021" />
	<xacro:property name="wheel_x_offset" value="${base_length / 2 - wheel_radius}" />
	<xacro:property name="wheel_y_offset" value="${base_width / 2 + wheel_width / 2}" />
	<xacro:property name="wheel_color" value="0 0 0 1" />

	<xacro:property name="xtion_x_position" value="0.01" />
	<xacro:property name="xtion_y_position" value="0" />
	<xacro:property name="xtion_z_position" value="0.04" />
	<xacro:property name="xtion_roll_position" value="0" />
	<xacro:property name="xtion_pitch_position" value="0" />
	<xacro:property name="xtion_yaw_position" value="0" />

	<material name="gray">
		<color rgba="0.5 0.5 0.5 0.8"/>
	</material>

	<material name="white">
		<color rgba="1 1 1 0.8"/>
	</material>

	<material name="black">
		<color rgba="0 0 0 0.8"/>
	</material>

	<material name="blue">
		<color rgba="0 0 0.8 0.8"/>
	</material>

	<xacro:macro name="default_inertial" params="mass">
		<inertial>
			<mass value="${mass}" />
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0"
				 izz="1.0" />
		</inertial>
	</xacro:macro>


	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:default_inertial mass="0.1"/>
	</link>

	<xacro:macro name="wheel" params="prefix reflect">

		<link name="${prefix}_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="0 0 0" xyz="0 0 0"/>
				<material name="black"/>
			</visual>
			<xacro:default_inertial mass="0.03"/>
		</link>

		<joint name="base_to_${prefix}_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="${prefix}_wheel"/>
			<origin xyz="${-wheel_x_offset} ${reflect*wheel_y_offset} 0" rpy="${pi / 2} 0 0"/>
			<axis xyz="0 1 0"/>
		</joint>

	</xacro:macro>

	<xacro:wheel prefix="right" reflect="1" />
	<xacro:wheel prefix="left" reflect="-1" />

    <xacro:asus_camera_model name="xtion" parent="base_link">
      <origin xyz="${xtion_x_position} ${xtion_y_position}  ${xtion_z_position}" rpy="${xtion_roll_position} ${xtion_pitch_position} ${xtion_yaw_position}"/>
    </xacro:asus_camera_model>

	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/</robotNamespace>
		</plugin>
	</gazebo>

</robot>
