#!/bin/bash

# read configuration
. ./env

if [ -z $SRCEXTLIST ]
then
	SRCEXTLIST='mp4 mkv mov avi'
fi

extlist=$(sed -E 's/ +/\\|/g' <<<"$SRCEXTLIST")

cd in && flist=`find . -type f -regex '.*\.\('${extlist}'\)$' -follow | sort` && cd -

IFS=$'\x0A'

for fn in $flist
do

odname="out/`dirname "$fn"`"
ofn="${odname}/`basename ${fn} .mp4`.mp4"
fn="in/$fn"

echo "PROCESSING $fn ..."

mkdir -p "$odname"

# make file if it does not exist
if [ ! -e "$ofn" ]; then

	aVF=()

	# test bitrate
	IFS=- read -r bt vw vh <<< `mediainfo --Output='Video;%BitRate%-%Width%-%Height%' "$fn"`
	if [ `expr ${bt} / 1000` -gt ${BITRATE} ]
	then
		echo "bitrate `expr $bt / 1000` is bigger than $BITRATE, processing..."
		if [ -z "${YRES}" ]
		then
			yres="-2"
		else
			yres=${YRES}
		fi
		if [ "${FORCE_SCALING}" -gt 0 ] || [ "${yres}" -gt 0 ] || [ ${vw} -gt ${XRES} ]
		then
			if [ ! "$FORCE_SCALING" -gt 0 ] && [ ! "$yres" -gt 0 ]
			then
				echo video width is wide so scaling is added \($vw \> $XRES\)
			fi
			aVF+=("scale=${XRES}:${yres}")
		else
			echo video width is not wide so no resizing \($vw \<= $XRES\)
		fi
		if [ -n "${ASPECT}" ]
		then
			aVF+=("setdar=${ASPECT}")
		fi
		VF=$(IFS=, ; echo "${aVF[*]}")
		if [ -n "${VF}" ]
		then
			VF="-vf ${VF}"
		fi
		cmd="ffmpeg -y -i \"$fn\" -b:a 56k -ar 44100 -b:v ${BITRATE}k $VF -f mp4 \"$ofn\""
	else
		echo "bitrate `expr $bt / 1000` is smaller than $BITRATE, symlinking"
		cmd="ln -s \"`pwd`/$fn\" \"$ofn\""
	fi
	echo Running $cmd
	eval $cmd
else
	echo exists, skipping
fi

done

echo Finished
