# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libcommands_py', [dirname(__file__)])
        except ImportError:
            import _libcommands_py
            return _libcommands_py
        if fp is not None:
            try:
                _mod = imp.load_module('_libcommands_py', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libcommands_py = swig_import_helper()
    del swig_import_helper
else:
    import _libcommands_py
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


C_PING = _libcommands_py.C_PING
C_STATE = _libcommands_py.C_STATE
C_MLEFT = _libcommands_py.C_MLEFT
C_MRIGHT = _libcommands_py.C_MRIGHT
C_MBOTH = _libcommands_py.C_MBOTH
C_MSTOP = _libcommands_py.C_MSTOP
C_RESET_COUNTERS = _libcommands_py.C_RESET_COUNTERS
C_WALK_AROUND = _libcommands_py.C_WALK_AROUND
C_MOVE2RELEASE = _libcommands_py.C_MOVE2RELEASE
R_OK_0 = _libcommands_py.R_OK_0
R_ERROR_0 = _libcommands_py.R_ERROR_0
R_VOLTS_1F = _libcommands_py.R_VOLTS_1F
R_MCOUNTS_2F = _libcommands_py.R_MCOUNTS_2F
R_MCURRENT_2F = _libcommands_py.R_MCURRENT_2F
R_MPOWER_2F = _libcommands_py.R_MPOWER_2F
R_MDIST_2F = _libcommands_py.R_MDIST_2F
R_DIST_1F = _libcommands_py.R_DIST_1F
R_IRDIST_1F = _libcommands_py.R_IRDIST_1F
R_MOTION_1F = _libcommands_py.R_MOTION_1F
R_HEADING_1F = _libcommands_py.R_HEADING_1F
R_COMPASS_3F = _libcommands_py.R_COMPASS_3F
R_ACC_3F = _libcommands_py.R_ACC_3F
R_ACCAVG_3F = _libcommands_py.R_ACCAVG_3F
R_ACCMAX_3F = _libcommands_py.R_ACCMAX_3F
R_HIT_1F = _libcommands_py.R_HIT_1F
R_GYRO_3F = _libcommands_py.R_GYRO_3F
R_TEMPERATURE_1F = _libcommands_py.R_TEMPERATURE_1F
R_PRESSURE_1F = _libcommands_py.R_PRESSURE_1F
R_END = _libcommands_py.R_END
MAGIC_BYTE = _libcommands_py.MAGIC_BYTE
# This file is compatible with both classic and new-style classes.


