<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="orange_on_track">
	<xacro:property name="base_width" value="0.105" />
	<xacro:property name="base_length" value="0.17" />
	<xacro:property name="base_height" value="0.043" />
	<xacro:property name="green_plate_width" value="0.105" />
	<xacro:property name="green_plate_length" value="0.17" />
	<xacro:property name="green_plate_height" value="0.001" />
	<xacro:property name="green_plate_z_offset" value="${base_height / 2 + 0.001}" />
	<xacro:property name="white_plate_width" value="0.20" />
	<xacro:property name="white_plate_length" value="0.245" />
	<xacro:property name="white_plate_height" value="0.009" />
	<xacro:property name="white_plate_x_offset" value="-0.015" />
	<xacro:property name="white_plate_z_offset" value="0.029" />
	<xacro:property name="stand_width" value="0.002" />
	<xacro:property name="stand_length" value="0.05" />
	<xacro:property name="stand_height" value="0.195" />
	<xacro:property name="wheel_radius" value="0.0235" />
	<xacro:property name="wheel_width" value="0.021" />
	<xacro:property name="wheel_x_offset" value="${green_plate_length / 2 - wheel_radius}" />
	<xacro:property name="wheel_y_offset" value="${green_plate_width / 2 + wheel_width / 2}" />
	<xacro:property name="wheel_color" value="0 0 0 1" />
	<xacro:property name="header_width" value="0.08" />
	<xacro:property name="header_length" value="0.04" />
	<xacro:property name="header_height" value="0.06" />
	<xacro:property name="header_x_offset" value="0.10" />
	<xacro:property name="header_z_offset" value="0.06" />

	<xacro:macro name="default_inertial" params="mass">
		<inertial>
			<mass value="${mass}" />
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0"
				 izz="1.0" />
		</inertial>
	</xacro:macro>


	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="gray">
				<color rgba="0.5 0.5 0.5 0"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:default_inertial mass="0.1"/>
	</link>

	<joint name="base_to_green_plate" type="fixed">
		<parent link="base_link"/>
		<child link="green_plate"/>
		<origin xyz="0 0 ${green_plate_z_offset}" rpy="0 0 0"/>
	</joint>

	<link name="green_plate">
		<visual>
			<geometry>
				<box size="${green_plate_length} ${green_plate_width} ${green_plate_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="green">
				<color rgba="0 1 0 0.5"/>
			</material>
		</visual>
		<xacro:default_inertial mass="0.02"/>
	</link>

	<joint name="green_plate_to_white_plate" type="fixed">
		<parent link="green_plate"/>
		<child link="white_plate"/>
		<origin xyz="0 0 ${white_plate_z_offset}" rpy="0 0 0"/>
	</joint>

	<link name="white_plate">
		<visual>
			<geometry>
				<box size="${white_plate_width} ${white_plate_length} ${white_plate_height}"/>
			</geometry>
			<origin xyz="${-white_plate_x_offset} 0 0" rpy="0 0 0"/>
			<material name="white">
				<color rgba="1 1 1 0.5"/>
			</material>
		</visual>
		<xacro:default_inertial mass="0.05"/>
	</link>

	<link name="left_stand">
		<visual>
			<geometry>
				<box size="${stand_length} ${stand_width} ${stand_height}"/>
			</geometry>
			<origin xyz="0 0 ${stand_height/2}" rpy="0 0 0"/>
			<material name="white">
				<color rgba="1 1 1 0.5"/>
			</material>
		</visual>
		<xacro:default_inertial mass="0.03"/>
	</link>

	<joint name="white_plate_to_left_stand" type="fixed">
		<parent link="white_plate"/>
		<child link="left_stand"/>
		<origin xyz="0 ${white_plate_width / 2} 0" rpy="0 0 0"/>
	</joint>

	<link name="right_stand">
		<visual>
			<geometry>
				<box size="${stand_length} ${stand_width} ${stand_height}"/>
			</geometry>
			<origin xyz="0 0 ${stand_height/2}" rpy="0 0 0"/>
			<material name="white">
				<color rgba="1 1 1 0.5"/>
			</material>
		</visual>
		<xacro:default_inertial mass="0.03"/>
	</link>

	<joint name="white_plate_to_right_stand" type="fixed">
		<parent link="white_plate"/>
		<child link="right_stand"/>
		<origin xyz="0 ${-white_plate_width / 2} 0" rpy="0 0 0"/>
	</joint>

	<link name="header">
		<visual>
			<geometry>
				<box size="${header_length} ${header_width} ${header_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="white">
				<color rgba="0 0 0.5 0.1"/>
			</material>
		</visual>
		<xacro:default_inertial mass="0.2"/>
	</link>

	<joint name="white_plate_to_header" type="fixed">
		<parent link="white_plate"/>
		<child link="header"/>
		<origin xyz="${header_x_offset} 0 ${header_z_offset}" rpy="0 0 0"/>
	</joint>


	<xacro:macro name="track" params="prefix reflect">

		<link name="${prefix}_rear_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="0 0 0" xyz="0 0 0"/>
				<material name="black">
					<color rgba="${wheel_color}"/>
				</material>
			</visual>
			<xacro:default_inertial mass="0.03"/>
		</link>

		<link name="${prefix}_fwd_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="0 0 0" xyz="0 0 0"/>
				<material name="black">
					<color rgba="${wheel_color}"/>
				</material>
			</visual>
			<xacro:default_inertial mass="0.03"/>
		</link>

		<joint name="base_to_${prefix}_rear_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="${prefix}_rear_wheel"/>
			<origin xyz="${-wheel_x_offset} ${reflect*wheel_y_offset} 0" rpy="${pi / 2} 0 0"/>
		</joint>

		<joint name="base_to_${prefix}_fwd_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="${prefix}_fwd_wheel"/>
			<origin xyz="${wheel_x_offset} ${reflect*wheel_y_offset} 0" rpy="${pi / 2} 0 0"/>
			<inertia
				ixx="1.0" ixy="0.0" ixz="0.0"
				iyy="1.0" iyz="0.0"
				izz="1.0"/>
		</joint>

		<transmission name="base_to_${prefix}_rear_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="base_to_${prefix}_rear_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
			<joint name="base_to_${prefix}_rear_wheel">
				<hardwareInterface>PositionJointInterface</hardwareInterface>
			</joint>
		</transmission>

	</xacro:macro>

	<xacro:track prefix="right" reflect="1" />
	<xacro:track prefix="left" reflect="-1" />

	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/</robotNamespace>
		</plugin>
	</gazebo>

</robot>
