# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/sda1/home/n800s/work/sourceforge/robotarr-code/gui/robotarr-qt4/gui/mainwindow.ui'
#
# Created: Fri Mar 16 20:06:48 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(539, 676)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_3 = QtGui.QFrame(self.centralWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout = QtGui.QFormLayout(self.frame_5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.L_Version = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Version.sizePolicy().hasHeightForWidth())
        self.L_Version.setSizePolicy(sizePolicy)
        self.L_Version.setMinimumSize(QtCore.QSize(30, 10))
        self.L_Version.setText(_fromUtf8(""))
        self.L_Version.setObjectName(_fromUtf8("L_Version"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.L_Version)
        self.label_2 = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.L_Battery = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Battery.sizePolicy().hasHeightForWidth())
        self.L_Battery.setSizePolicy(sizePolicy)
        self.L_Battery.setMinimumSize(QtCore.QSize(30, 10))
        self.L_Battery.setText(_fromUtf8(""))
        self.L_Battery.setObjectName(_fromUtf8("L_Battery"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.L_Battery)
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.L_Error = QtGui.QLabel(self.frame_5)
        self.L_Error.setObjectName(_fromUtf8("L_Error"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.L_Error)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.frame_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.L_Pitch = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Pitch.sizePolicy().hasHeightForWidth())
        self.L_Pitch.setSizePolicy(sizePolicy)
        self.L_Pitch.setText(_fromUtf8(""))
        self.L_Pitch.setObjectName(_fromUtf8("L_Pitch"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.L_Pitch)
        self.label_5 = QtGui.QLabel(self.frame_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.L_Roll = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Roll.sizePolicy().hasHeightForWidth())
        self.L_Roll.setSizePolicy(sizePolicy)
        self.L_Roll.setText(_fromUtf8(""))
        self.L_Roll.setObjectName(_fromUtf8("L_Roll"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.L_Roll)
        self.label_6 = QtGui.QLabel(self.frame_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.L_Orientation = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Orientation.sizePolicy().hasHeightForWidth())
        self.L_Orientation.setSizePolicy(sizePolicy)
        self.L_Orientation.setText(_fromUtf8(""))
        self.L_Orientation.setObjectName(_fromUtf8("L_Orientation"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.L_Orientation)
        self.label_7 = QtGui.QLabel(self.frame_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.L_Direction = QtGui.QLabel(self.frame_6)
        self.L_Direction.setText(_fromUtf8(""))
        self.L_Direction.setObjectName(_fromUtf8("L_Direction"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.L_Direction)
        self.label_13 = QtGui.QLabel(self.frame_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.frame_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.frame_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_15)
        self.L_Lx = QtGui.QLabel(self.frame_6)
        self.L_Lx.setText(_fromUtf8(""))
        self.L_Lx.setObjectName(_fromUtf8("L_Lx"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.L_Lx)
        self.L_Ly = QtGui.QLabel(self.frame_6)
        self.L_Ly.setText(_fromUtf8(""))
        self.L_Ly.setObjectName(_fromUtf8("L_Ly"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.L_Ly)
        self.L_Lz = QtGui.QLabel(self.frame_6)
        self.L_Lz.setText(_fromUtf8(""))
        self.L_Lz.setObjectName(_fromUtf8("L_Lz"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.L_Lz)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_7)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.frame_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.L_SpeedLeft = QtGui.QLabel(self.frame_7)
        self.L_SpeedLeft.setMinimumSize(QtCore.QSize(50, 0))
        self.L_SpeedLeft.setText(_fromUtf8(""))
        self.L_SpeedLeft.setObjectName(_fromUtf8("L_SpeedLeft"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.L_SpeedLeft)
        self.label_9 = QtGui.QLabel(self.frame_7)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.L_SpeedRight = QtGui.QLabel(self.frame_7)
        self.L_SpeedRight.setText(_fromUtf8(""))
        self.L_SpeedRight.setObjectName(_fromUtf8("L_SpeedRight"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.L_SpeedRight)
        self.label_10 = QtGui.QLabel(self.frame_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.L_Gx = QtGui.QLabel(self.frame_7)
        self.L_Gx.setText(_fromUtf8(""))
        self.L_Gx.setObjectName(_fromUtf8("L_Gx"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.L_Gx)
        self.label_11 = QtGui.QLabel(self.frame_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.L_Gy = QtGui.QLabel(self.frame_7)
        self.L_Gy.setText(_fromUtf8(""))
        self.L_Gy.setObjectName(_fromUtf8("L_Gy"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.L_Gy)
        self.label_12 = QtGui.QLabel(self.frame_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.L_Gz = QtGui.QLabel(self.frame_7)
        self.L_Gz.setText(_fromUtf8(""))
        self.L_Gz.setObjectName(_fromUtf8("L_Gz"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.L_Gz)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.centralWidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_8 = QtGui.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.L_RawSensor0 = QtGui.QLabel(self.frame_8)
        self.L_RawSensor0.setText(_fromUtf8(""))
        self.L_RawSensor0.setAlignment(QtCore.Qt.AlignCenter)
        self.L_RawSensor0.setObjectName(_fromUtf8("L_RawSensor0"))
        self.horizontalLayout_3.addWidget(self.L_RawSensor0)
        self.L_RawSensor1 = QtGui.QLabel(self.frame_8)
        self.L_RawSensor1.setText(_fromUtf8(""))
        self.L_RawSensor1.setAlignment(QtCore.Qt.AlignCenter)
        self.L_RawSensor1.setObjectName(_fromUtf8("L_RawSensor1"))
        self.horizontalLayout_3.addWidget(self.L_RawSensor1)
        self.L_RawSensor2 = QtGui.QLabel(self.frame_8)
        self.L_RawSensor2.setText(_fromUtf8(""))
        self.L_RawSensor2.setAlignment(QtCore.Qt.AlignCenter)
        self.L_RawSensor2.setObjectName(_fromUtf8("L_RawSensor2"))
        self.horizontalLayout_3.addWidget(self.L_RawSensor2)
        self.L_RawSensor3 = QtGui.QLabel(self.frame_8)
        self.L_RawSensor3.setText(_fromUtf8(""))
        self.L_RawSensor3.setAlignment(QtCore.Qt.AlignCenter)
        self.L_RawSensor3.setObjectName(_fromUtf8("L_RawSensor3"))
        self.horizontalLayout_3.addWidget(self.L_RawSensor3)
        self.L_RawSensor4 = QtGui.QLabel(self.frame_8)
        self.L_RawSensor4.setText(_fromUtf8(""))
        self.L_RawSensor4.setAlignment(QtCore.Qt.AlignCenter)
        self.L_RawSensor4.setObjectName(_fromUtf8("L_RawSensor4"))
        self.horizontalLayout_3.addWidget(self.L_RawSensor4)
        self.verticalLayout.addWidget(self.frame_8)
        self.W_Compass = W_Compass(self.frame_4)
        self.W_Compass.setMinimumSize(QtCore.QSize(100, 199))
        self.W_Compass.setObjectName(_fromUtf8("W_Compass"))
        self.verticalLayout.addWidget(self.W_Compass)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(197, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButton_7 = QtGui.QToolButton(self.frame)
        self.toolButton_7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_7.setText(_fromUtf8(""))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.gridLayout.addWidget(self.toolButton_7, 0, 0, 1, 1)
        self.TB_Forward = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Forward.sizePolicy().hasHeightForWidth())
        self.TB_Forward.setSizePolicy(sizePolicy)
        self.TB_Forward.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Forward.setAutoRepeat(True)
        self.TB_Forward.setObjectName(_fromUtf8("TB_Forward"))
        self.gridLayout.addWidget(self.TB_Forward, 0, 1, 1, 1)
        self.toolButton_8 = QtGui.QToolButton(self.frame)
        self.toolButton_8.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_8.sizePolicy().hasHeightForWidth())
        self.toolButton_8.setSizePolicy(sizePolicy)
        self.toolButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_8.setText(_fromUtf8(""))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.gridLayout.addWidget(self.toolButton_8, 0, 2, 1, 1)
        self.TB_Left = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Left.sizePolicy().hasHeightForWidth())
        self.TB_Left.setSizePolicy(sizePolicy)
        self.TB_Left.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Left.setAutoRepeat(True)
        self.TB_Left.setObjectName(_fromUtf8("TB_Left"))
        self.gridLayout.addWidget(self.TB_Left, 1, 0, 1, 1)
        self.TB_Stop = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Stop.sizePolicy().hasHeightForWidth())
        self.TB_Stop.setSizePolicy(sizePolicy)
        self.TB_Stop.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Stop.setAutoRepeat(True)
        self.TB_Stop.setObjectName(_fromUtf8("TB_Stop"))
        self.gridLayout.addWidget(self.TB_Stop, 1, 1, 1, 1)
        self.TB_Right = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Right.sizePolicy().hasHeightForWidth())
        self.TB_Right.setSizePolicy(sizePolicy)
        self.TB_Right.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Right.setAutoRepeat(True)
        self.TB_Right.setObjectName(_fromUtf8("TB_Right"))
        self.gridLayout.addWidget(self.TB_Right, 1, 2, 1, 1)
        self.toolButton_6 = QtGui.QToolButton(self.frame)
        self.toolButton_6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_6.setText(_fromUtf8(""))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.gridLayout.addWidget(self.toolButton_6, 2, 0, 1, 1)
        self.TB_Back = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Back.sizePolicy().hasHeightForWidth())
        self.TB_Back.setSizePolicy(sizePolicy)
        self.TB_Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Back.setAutoRepeat(True)
        self.TB_Back.setObjectName(_fromUtf8("TB_Back"))
        self.gridLayout.addWidget(self.TB_Back, 2, 1, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.frame)
        self.toolButton_9.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_9.setText(_fromUtf8(""))
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.gridLayout.addWidget(self.toolButton_9, 2, 2, 1, 1)
        self.TB_Keep = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Keep.sizePolicy().hasHeightForWidth())
        self.TB_Keep.setSizePolicy(sizePolicy)
        self.TB_Keep.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Keep.setObjectName(_fromUtf8("TB_Keep"))
        self.gridLayout.addWidget(self.TB_Keep, 3, 0, 1, 1)
        self.TB_NoKeep = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_NoKeep.sizePolicy().hasHeightForWidth())
        self.TB_NoKeep.setSizePolicy(sizePolicy)
        self.TB_NoKeep.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_NoKeep.setObjectName(_fromUtf8("TB_NoKeep"))
        self.gridLayout.addWidget(self.TB_NoKeep, 3, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Robotarr", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Battery:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.L_Error.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Pitch:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Roll:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Orientation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Lx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Ly:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Lz:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Speed Left:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Speed Right:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Gx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Gy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Gz:", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Forward.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Forward.setShortcut(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Left.setText(QtGui.QApplication.translate("MainWindow", "Turn\n"
"Left", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Left.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Stop.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Right.setText(QtGui.QApplication.translate("MainWindow", "Turn\n"
"Right", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Right.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Back.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Back.setShortcut(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Keep.setText(QtGui.QApplication.translate("MainWindow", "Keep", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_NoKeep.setText(QtGui.QApplication.translate("MainWindow", "No Keep", None, QtGui.QApplication.UnicodeUTF8))

from w_compass import W_Compass

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

