# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/sda1/home/n800s/work/sourceforge/robotarr-code/gui/robotarr-qt4/gui/mainwindow.ui'
#
# Created: Sat Mar 10 14:41:38 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(444, 489)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_3 = QtGui.QFrame(self.centralWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.L_Version = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Version.sizePolicy().hasHeightForWidth())
        self.L_Version.setSizePolicy(sizePolicy)
        self.L_Version.setMinimumSize(QtCore.QSize(30, 10))
        self.L_Version.setText(_fromUtf8(""))
        self.L_Version.setObjectName(_fromUtf8("L_Version"))
        self.gridLayout_2.addWidget(self.L_Version, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.L_Battery = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Battery.sizePolicy().hasHeightForWidth())
        self.L_Battery.setSizePolicy(sizePolicy)
        self.L_Battery.setMinimumSize(QtCore.QSize(30, 10))
        self.L_Battery.setText(_fromUtf8(""))
        self.L_Battery.setObjectName(_fromUtf8("L_Battery"))
        self.gridLayout_2.addWidget(self.L_Battery, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.centralWidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(197, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButton_7 = QtGui.QToolButton(self.frame)
        self.toolButton_7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_7.setText(_fromUtf8(""))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.gridLayout.addWidget(self.toolButton_7, 0, 0, 1, 1)
        self.TB_Forward = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Forward.sizePolicy().hasHeightForWidth())
        self.TB_Forward.setSizePolicy(sizePolicy)
        self.TB_Forward.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Forward.setAutoRepeat(True)
        self.TB_Forward.setObjectName(_fromUtf8("TB_Forward"))
        self.gridLayout.addWidget(self.TB_Forward, 0, 1, 1, 1)
        self.toolButton_8 = QtGui.QToolButton(self.frame)
        self.toolButton_8.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_8.sizePolicy().hasHeightForWidth())
        self.toolButton_8.setSizePolicy(sizePolicy)
        self.toolButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_8.setText(_fromUtf8(""))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.gridLayout.addWidget(self.toolButton_8, 0, 2, 1, 1)
        self.TB_Left = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Left.sizePolicy().hasHeightForWidth())
        self.TB_Left.setSizePolicy(sizePolicy)
        self.TB_Left.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Left.setAutoRepeat(True)
        self.TB_Left.setObjectName(_fromUtf8("TB_Left"))
        self.gridLayout.addWidget(self.TB_Left, 1, 0, 1, 1)
        self.TB_Stop = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Stop.sizePolicy().hasHeightForWidth())
        self.TB_Stop.setSizePolicy(sizePolicy)
        self.TB_Stop.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Stop.setAutoRepeat(True)
        self.TB_Stop.setObjectName(_fromUtf8("TB_Stop"))
        self.gridLayout.addWidget(self.TB_Stop, 1, 1, 1, 1)
        self.TB_Right = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Right.sizePolicy().hasHeightForWidth())
        self.TB_Right.setSizePolicy(sizePolicy)
        self.TB_Right.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Right.setAutoRepeat(True)
        self.TB_Right.setObjectName(_fromUtf8("TB_Right"))
        self.gridLayout.addWidget(self.TB_Right, 1, 2, 1, 1)
        self.toolButton_6 = QtGui.QToolButton(self.frame)
        self.toolButton_6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_6.setText(_fromUtf8(""))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.gridLayout.addWidget(self.toolButton_6, 2, 0, 1, 1)
        self.TB_Back = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Back.sizePolicy().hasHeightForWidth())
        self.TB_Back.setSizePolicy(sizePolicy)
        self.TB_Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TB_Back.setAutoRepeat(True)
        self.TB_Back.setObjectName(_fromUtf8("TB_Back"))
        self.gridLayout.addWidget(self.TB_Back, 2, 1, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.frame)
        self.toolButton_9.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_9.setText(_fromUtf8(""))
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.gridLayout.addWidget(self.toolButton_9, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Battery:", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Forward.setText(QtGui.QApplication.translate("MainWindow", "Go\n"
"Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Forward.setShortcut(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Left.setText(QtGui.QApplication.translate("MainWindow", "Turn\n"
"Left", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Left.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Stop.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Right.setText(QtGui.QApplication.translate("MainWindow", "Turn\n"
"Right", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Right.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Back.setText(QtGui.QApplication.translate("MainWindow", "Go\n"
"Back", None, QtGui.QApplication.UnicodeUTF8))
        self.TB_Back.setShortcut(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

